//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stadio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class abbonamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public abbonamento()
        {
            this.posto = new HashSet<posto>();
        }
    
        public int idAbbonamento { get; set; }
        public decimal costo { get; set; }
        public string CF { get; set; }
        public string anno { get; set; }
        public int idTipologia { get; set; }
    
        public virtual TipologiaEvento TipologiaEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<posto> posto { get; set; }
    }
}
