//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stadio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public evento()
        {
            this.biglietto = new HashSet<biglietto>();
            this.posto = new HashSet<posto>();
        }
    
        public int idEvento { get; set; }
        public int postiDisponibili { get; set; }
        public int abbonamentiDisponibili { get; set; }
        public string nomeEvento { get; set; }
        public System.DateTime dataEvento { get; set; }
        public int idTipologia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<biglietto> biglietto { get; set; }
        public virtual TipologiaEvento TipologiaEvento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<posto> posto { get; set; }
    }
}
