//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stadio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class posto
    {
        public int idPosto { get; set; }
        public int numeroPosto { get; set; }
        public string nomeSettore { get; set; }
        public string nomeAnello { get; set; }
        public string isDisponibile { get; set; }
        public Nullable<int> evento { get; set; }
        public Nullable<int> abbonamento { get; set; }
    
        public virtual abbonamento abbonamento1 { get; set; }
        public virtual evento evento1 { get; set; }
    }
}
