//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stadio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public string nomeUtente { get; set; }
        public string autPassword { get; set; }
        public string ruolo { get; set; }
        public string nome { get; set; }
        public string cognome { get; set; }
        public string CF { get; set; }
        public int eta { get; set; }
        public string sesso { get; set; }
    }
}
