//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stadio.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StadioDBEntities : DbContext
    {
        public StadioDBEntities()
            : base("name=StadioDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<abbonamento> abbonamento { get; set; }
        public virtual DbSet<biglietto> biglietto { get; set; }
        public virtual DbSet<evento> evento { get; set; }
        public virtual DbSet<posto> posto { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<TipologiaEvento> TipologiaEvento { get; set; }
    }
}
